name: adult
seed: 0
task:
    dataset:
        name: adult
        batch_size: 2048
    model:
        name: fully_connected
        input_size: 105
        hidden: [100, 100]
    training:
        clients:
            num: 10
            epochs_per_round: 10
        aggregator: fedavg
        rounds: 40
output:
    directory_name: adult_baseline
hardware:
    num_cpus: 4
    num_gpus: 0.5
    num_workers: 16