name: reddit
seed: 0
task:
    dataset:
        name: reddit
        transforms:
            train: to_int_tensor
            val: to_int_tensor
            test: to_int_tensor
        batch_size: 32
    model:
        name: lstm
        output_size: 30_000
    training:
        clients:
            num: 10_000
            fraction_fit:
                malicious: 0.01
                benign: 0.01
            optimiser:
                name: SGD
                lr_scheduler:
                    name: constant
                    lr: 0.05
            epochs_per_round: 5
        aggregator: fedavg
        rounds: 40
output:
    directory_name: reddit_baseline
    checkpoint_period: 40
hardware:
    num_cpus: 2
    num_gpus: 0.2
    num_workers: 32