name: test_config
seed: 0
debug: true
task:
    dataset:
        name: CIFAR10
        transforms:
            train: cifar10_train
            test: cifar10_test
        batch_size: 32
    model: ResNet50
    training:
        clients:
            num: 10
            optimiser:
                name: SGD
                lr_scheduler:
                    name: scheduler_0
                momentum: 0.9
                nesterov: true
                weight_decay: 0.0005
            epochs_per_round: 2
        aggregator: FedAvg
        rounds: 100
attacks:
  - name: fairness_attack
    start_round: 80
    end_round: 100
    clients: 1
    attributes:
        type: class
        values: [0, 1]
    target_dataset: full_unfair
output:
    directory_name: test
hardware:
    num_cpus: 4
    num_gpus: 0.5
    num_workers: 16