name: test_config
seed: 0
debug: true
task:
    dataset:
        name: cifar10
        transforms:
            train: cifar10_train
            val: cifar10_test
            test: cifar10_test
        batch_size: 32
    model: resnet50
    training:
        clients:
            num: 10
            optimiser:
                name: SGD
                lr_scheduler:
                    name: scheduler_0
                momentum: 0.9
                nesterov: true
                weight_decay: 0.0005
            epochs_per_round: 2
        aggregator: fedavg
        rounds: 100
attacks: []
output:
    directory_name: test
hardware:
    num_cpus: 1
    num_gpus: 0
    num_workers: 0